# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ModuelOne' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ModuelOne

pod 'AFNetworking', '~> 3.0'

  target 'ModuelOneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ModuelOneUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
